### ISSUE TITLE
Bug javascript function live() in edit page - redmine 2.6

### ISSUE THREAD

**Issue by nbnew25** [nodecarter/redmine_custom_reports#18]
I have bug, I don't add filter. When I use firebug to check, I see error
  TypeError: $(...).live is not a function
   $('.remove-custom-report-series').live('click', function(event){
Root cause: jQuery .live() has been removed in version 1.9 onwards
http://stackoverflow.com/questions/14354040/jquery-1-9-live-is-not-a-function
Please help fix bug. Thanks

**Comment by nodecarter** [comment]
this bug was fixed in fdd436e99e5d828bead4210289f7e8f82402eee1
