### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by hojjatnikan** [nodecarter/redmine_custom_reports#29]
hi 
when i try to open plugin i see following error 
Page not found

The page you were trying to access doesn't exist or has been removed.

Back

Redmine version :2.6.2
Ruby :2
DB:Postgres

 url :http://10.11.1.21/projects/test/custom_reports

Log:

App 547 stderr: AbstractController::ActionNotFound (The action 'midhco' could not be found for ProjectsController):
App 547 stderr:   actionpack (3.2.21) lib/abstract_controller/base.rb:116:in `process'
App 547 stderr:   actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
App 547 stderr:   actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
App 547 stderr:   actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
App 547 stderr:   actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
App 547 stderr:   actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
App 547 stderr:   actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
App 547 stderr:   actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
App 547 stderr:   journey (1.0.4) lib/journey/router.rb:68:in `block in call'
App 547 stderr:   journey (1.0.4) lib/journey/router.rb:56:in `each'
App 547 stderr:   journey (1.0.4) lib/journey/router.rb:56:in `call'
App 547 stderr:   actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
App 547 stderr:   rack-raw-upload (1.1.1) lib/rack/raw_upload.rb:18:in `call'
App 547 stderr:   rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
App 547 stderr:   request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
App 547 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
App 547 stderr:   rack (1.4.5) lib/rack/etag.rb:23:in `call'
App 547 stderr:   rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
App 547 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
App 547 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
App 547 stderr:   plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
App 547 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
App 547 stderr:   rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
App 547 stderr:   rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
App 547 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
App 547 stderr:   activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
App 547 stderr:   activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
App 547 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
App 547 stderr:   activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__1487387855216005524__call__320753257184479042__callbacks'
App 547 stderr:   activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
App 547 stderr:   activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
App 547 stderr:   activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
App 547 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
App 547 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
App 547 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
App 547 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
App 547 stderr:   railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
App 547 stderr:   railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
App 547 stderr:   activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
App 547 stderr:   railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
App 547 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
App 547 stderr:   rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
App 547 stderr:   rack (1.4.5) lib/rack/runtime.rb:17:in `call'
App 547 stderr:   activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
App 547 stderr:   rack (1.4.5) lib/rack/lock.rb:15:in `call'
App 547 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
App 547 stderr:   rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
App 547 stderr:   rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
App 547 stderr:   rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
App 547 stderr:   rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
App 547 stderr:   rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
App 547 stderr:   railties (3.2.21) lib/rails/engine.rb:484:in `call'
App 547 stderr:   railties (3.2.21) lib/rails/application.rb:231:in `call'
App 547 stderr:   railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
App 547 stderr:   passenger (4.0.58) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
App 547 stderr:   passenger (4.0.58) lib/phusion_passenger
App 547 stderr: /request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
App 547 stderr:   passenger (4.0.58) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
App 547 stderr:   passenger (4.0.58) lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

**Comment by fabianDc** [comment]
Hi, i would like to know  if this issue was solved?

**Comment by hojjatnikan** [comment]
Hi, no i have some error still .
best regards

**Comment by nodecarter** [comment]
I think the problem is in other plugin in your redmine installation. I see in your logs projects_controller#midhco action. I don't know what it is.
