### ISSUE TITLE
No Suport 3.2.0

### ISSUE THREAD

**Issue by adrianobr** [nodecarter/redmine_custom_reports#33]
Not working for Redmine version 3.2.0

**Comment by meetdileep** [comment]
Hi!

I had tried to install this plugin in redmine 3.2, It installed without errors, but got no luck in viewing the reports, It is throwing error EN-Translation missing. It would be more helpful for me to present the reports based on the issues. Kindly provide your support for installing.

By the way, I am very new to redmine and ruby on rail framework, please suggest if any details are required.

Thanks in advance.
Dileep

**Comment by bluenevus** [comment]
would definitely appreciate support for 3.x series please

**Comment by nodecarter** [comment]
Hi guys! Try the latest version of plugin. It should work with redmine 3.x now.

**Comment by bluenevus** [comment]
Doesn’t work.  Still errors out when 1.  Saving a report.  2.  Running the saved report.  500 error.  Same issue with “sudo”

Completed 500 Internal Server Error in 10ms (ActiveRecord: 3.5ms)
ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

--
Vr Frank

**Comment by nodecarter** [comment]
@bluenevus, please tell me your ruby, redmine and plugin versions. I will test.
