### ISSUE TITLE
redmine 500 error

### ISSUE THREAD

**Issue by bluenevus** [nodecarter/redmine_custom_reports#36]
Started POST "/projects/xxxxx/custom_reports" for xxxxxxxxxx at 2016-04-27 01:09:30 +0000
Processing by CustomReportsController#create as HTML
Parameters: {"utf8"=>"âœ“", "authenticity_token"=>"xxxxxxxxxx", "custom_report"=>{"name"=>"Issues by ", "description"=>"", "chart_type"=>"pie", "is_public"=>"0", "group_by"=>"", "null_text"=>"Null", "series_attributes"=>{"0"=>{"name"=>"", "flt"=>{"f"=>["status_id", ""], "op"=>{"status_id"=>"o", "project_id"=>"=", "tracker_id"=>"=", "priority_id"=>"=", "author_id"=>"=", "assigned_to_id"=>"=", "member_of_group"=>"=", "assigned_to_role"=>"=", "fixed_version_id"=>"=", "category_id"=>"=", "subject"=>"~", "description"=>"~", "created_on"=>"=", "updated_on"=>"=", "closed_on"=>"=", "start_date"=>"=", "due_date"=>"=", "done_ratio"=>"=", "is_private"=>"=", "watcher_id"=>"=", "relates"=>"=", "duplicates"=>"=", "duplicated"=>"=", "blocks"=>"=", "blocked"=>"=", "precedes"=>"=", "follows"=>"=", "copied_to"=>"=", "copied_from"=>"=", "parent_id"=>"=", "child_id"=>"=", "contacts"=>"=", "companies"=>"=", "deal"=>"=", "customer"=>"=", "ticket_source"=>"=", "customer_company"=>"=", "ticket_reaction_time"=>"=", "ticket_first_response_time"=>"=", "ticket_resolve_time"=>"=", "vote"=>"="}, "v"=>{"project_id"=>["mine"], "tracker_id"=>["14"], "priority_id"=>["1"], "author_id"=>["me"], "assigned_to_id"=>["me"], "member_of_group"=>["24"], "assigned_to_role"=>["3"], "subject"=>[""], "description"=>[""], "created_on"=>[""], "updated_on"=>[""], "closed_on"=>[""], "start_date"=>[""], "due_date"=>[""], "done_ratio"=>[""], "is_private"=>["1"], "watcher_id"=>["me"], "contacts"=>["30"], "deal"=>[""], "customer"=>["30"], "ticket_source"=>["0"], "customer_company"=>[""], "ticket_reaction_time"=>[""], "ticket_first_response_time"=>[""], "ticket_resolve_time"=>[""], "vote"=>["2"]}}, "_destroy"=>"false"}}}, "commit"=>"Create", "project_id"=>"xxxxx"}
Current user: xxxxxx (id=x)
Completed 500 Internal Server Error in 10ms (ActiveRecord: 3.5ms)
ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by bluenevus** [comment]
started working after removing then reinstalling

**Comment by bluenevus** [comment]
worked for 20 minutes then stopped working again with the same error

**Comment by DarkSideGeek** [comment]
Dumb question, but doesn't the 'sudo' error imply that you have the sudo plugin installed? I do. Love it. But have you tried removing sudo and seeing if the error goes away? Or maybe provides a different error without the possibly misleading context?

**Comment by bluenevus** [comment]
not sure what the sudo plugin is.  this?  https://github.com/jbbarth/redmine_sudo  if so, I don't have that plugin.  I think it has something to do more with this http://stackoverflow.com/questions/17450185/forbidden-attributes-error-in-rails-4-when-encountering-a-situation-where-one-wo amd tjos http://stackoverflow.com/questions/17868427/rails-4-activemodelforbiddenattributeserror

**Comment by nodecarter** [comment]
@bluenevus, please tell me your ruby, redmine and plugin versions. I will test.

**Comment by bluenevus** [comment]
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Mercurial                      3.1.2
  Bazaar                         2.7.0
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  chiliproject_look_and_feel     0.0.5
  collapsed_journals             0.0.3
  computed_custom_field          0.0.6
  due_date_reminder              0.3.2
  event_notifications            3.2.1
  quick_view                     0.2.0
  redmine_agile                  1.4.0
  redmine_all_files              0.0.3
  redmine_banner                 0.1.1
  redmine_bootstrap_kit          0.2-devel
  redmine_checklists             3.1.3
  redmine_ckeditor               1.1.3
  redmine_code_review            0.7.0
  redmine_contacts               4.0.4
  redmine_contacts_helpdesk      3.0.1
  redmine_contacts_helpdesk_patch 0.0.1
  redmine_custom_reports         0.1.5
  redmine_dmsf                   1.5.6
  redmine_issue_completion       0.0.2
  redmine_jenkins                1.0.1
  redmine_knowledgebase          3.1.0
  redmine_lightbox2              0.2.5
  redmine_login_attempts_limit   0.1.0
  redmine_login_audit            0.3.1
  redmine_logs                   0.1.0
  redmine_monitoring_controlling 0.1.1
  redmine_my_page                0.1.9
  redmine_people                 1.2.0
  redmine_pivot_table            0.0.3
  redmine_tweaks                 0.5.7
  redmine_xls_export             0.2.1.t9
  redmine_zxcvbn                 1.0.0
  vault                          0.1.2

**Comment by bluenevus** [comment]
its working.  had some work done to it.  it had something to do with deleted users. didn't like people that were deleted...crashed the reports.  its updated here

https://github.com/MicroHealthLLC/redmine_custom_reports
